### ISSUE TITLE
Is it possible to set configs for multiple plugins at once?

### ISSUE THREAD

**Issue by BigAndini** [geerlingguy/ansible-role-munin-node#16]
Hey,

is there a way to set the same config for multiple plugins at once? I thought about something like:

`
munin_node_config: {
  [ "diskstats", "iostat" ]: { "user": "root" }
}
`
instead of:
`
munin_node_config: {
  "diskstats": { "user": "root" },
  "iostat": { "user": "root" }
}
`

For this simple example it's no big deal, but I have some munin plugin with more complex configurations which I'd like to set to up to 8 plugins. Once there are changes to the configuration with such a solution there would be no need to adjust the config in multiple parts of the file.

**Comment by inbaz** [comment]
I'm still interested in a solution. :)

**Comment by BigAndini** [comment]
I'm still interested in a solution.
