### ISSUE TITLE
Fails the first time it runs

### ISSUE THREAD

**Issue by optize** [geerlingguy/ansible-role-munin-node#4]
We've reproduced this on every Ubuntu 14.04 box, however this step in the config fails the first time it installs Munin.
--
NOTIFIED: [geerlingguy.munin-node | restart munin-node] ***********************
failed: [wwwdev] => {"failed": true}
msg: Pid_file already exists for running process (14947)... aborting

FATAL: all hosts have already failed -- aborting
--
Future runs seem to be fine, however I do not believe they actually restart munin-node.

**Comment by geerlingguy** [comment]
I have not seen this happen on either Ubuntu or CentOS (tested on 14/12 and 7/6 within the past week)...  closing the issue for now, but if you can still reproduce, please let me know what environment you're finding this in—what hosting provider, or virtual machine provider, the image you're using, etc.

My best guess is maybe munin is already installed on the server when you run the role the first time, maybe?
