### ISSUE TITLE
Rename file /etc/munin/plugin-conf.d/ansible.conf to zzz-ansible.conf

### ISSUE THREAD

**Issue by henderbj** [geerlingguy/ansible-role-munin-node#8]
The file ansible.conf should be renamed to something like zzz-ansible.conf, in order to be read last and override default configuration of munin-node file, all on /etc/munin/plugin-conf.d/ directory.

For example, I was trying to change [df*] section, but on ansible.conf it don't overrides defaults, but on zzz-ansible.conf it does override defaults.

My suggestion is simply follow Munin's documentation one (on https://munin.readthedocs.io/en/latest/plugin/use.html#configuring):
"To make sure that plugin configurations are updated with software updates admins should not change the file munin-node which is delivered with the munin package. Instead place customized configuration in a file called zzz-myconf. As the config files are read in alphabetical order, this file is read last and will override configuration data found in the other files."
Well, I hope it helps.

**Comment by geerlingguy** [comment]
Good idea! I hadn't run into this specific issue, but I see what you're saying. This shouldn't be too difficult a change, though it would necessitate a major version bump as the template file is changing.

**Comment by henderbj** [comment]
In fact is a line change in code:
Only rename the string "ansible.conf" to "zzz-ansible.conf", or whatever other name you want to use. Didn't create a PR because of too simple patch ;)

**Comment by henderbj** [comment]
I noticed that ansible.conf is no used on any other part of the code (apart of README.md), so possibly no need to make change happen in a major version bump.

**Comment by zorun** [comment]
You need to handle the rename properly, by removing "ansible.conf" in the role.  Otherwise, the file will remain on all machines, will not get updated anymore, and will override anything defined in "zzz-ansible.conf".  That would not be helpful!

**Comment by henderbj** [comment]
Not really. The last file read overrides same configurations on previous files. So, if you have a section [df*] on ansible.conf and zzz-ansible.conf, the section on the last file will be used. Of course, its better to be extra safe and avoid having same section on several files, so its better to ensure ansible.conf doesn't exist anymore.

**Comment by amedee** [comment]
So, has this been done?
And if not, ok if I submit a pull request?
And if I submit a pull request, will it get merged?
